spring.application.name=job-tracker

management.endpoints.web.exposure.include=health
management.health.db.enabled=true
management.endpoint.health.show-details=always

spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.driver-class-name=org.postgresql.Driver

# Local development fallback only.
# On EKS, these are overridden by environment variables
# injected from AWS Parameter Store and Secrets Manager.
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=demo
spring.datasource.password=changeme

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Spring Data JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false